export interface Competitor { id: number; name: string; platform: string; channelId: string; url: string; createdAt: string }
export interface CompetitorCreate { name: string; platform: string; channel_id: string; url: string }
export interface SocialContent { id: number; competitorId: number; platform: string; contentId: string; title: string; description: string; url: string; publishedAt: string; createdAt?: string; competitor?: { name: string } }
export interface PerformanceData extends SocialContent { competitorName: string; views: number; likes: number; comments: number; shares: number | null; capturedAt: string | null }
export interface SocialMetric { id: number; socialContentId: number; views: number; likes: number; comments: number; shares: number | null; capturedAt: string; socialContent: SocialContent & { competitor: { name: string } } }
export interface AiAnalysis { id: number; contentId: number; topic: string; category: string; contentType: string; sentiment: string; keywords: unknown; summary: string; targetAudience: string; keyMessage: string; createdAt: string; socialContent: SocialContent & { competitor: { name: string } } }
export interface PerformanceAnalysis { id: number; competitorId: number; platform: string; videoCount: number; totalViews: number; totalLikes: number; totalComments: number; totalEngagement: number; averageViews: number; averageLikes: number; averageComments: number; engagementRate: number; averageLikeRate: number; averageCommentRate: number; performanceRank: number; createdAt: string; competitor: { name: string; channelId: string; url: string } }
export interface MonitoringMetricSnapshot { views: number; likes: number; comments: number; shares: number | null; capturedAt: string }
export interface MonitoringData { contentId: string; socialContentId: number; competitorId: number; competitorName: string; platform: string; title: string; metrics: MonitoringMetricSnapshot[] }
export interface MonitoringAlert { id: number; contentId: number; competitorId: number; platform: string; alertType: 'views_growth' | 'likes_growth' | 'comments_growth' | string; message: string; viewsChange: number; likesChange: number; commentsChange: number; viewsGrowthRate: number; likesGrowthRate: number; commentsGrowthRate: number; createdAt: string; competitor?: { name: string } | null; socialContent?: { contentId: string; title: string; url: string; platform: string } | null }
